#!/bin/sh

set -eu

for hwmon in /sys/class/hwmon/hwmon*; do
    [ -r "${hwmon}/name" ] || continue
    [ "$(cat "${hwmon}/name")" = "aspeed_pwm_tacho" ] || continue

    for pwm in "${hwmon}"/pwm[1-6]; do
        [ -e "${pwm}" ] || continue
        printf '%s\n' 255 > "${pwm}"
    done
done
