# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "trx40d8-2n2t-layer"
BBFILE_PATTERN_trx40d8-2n2t-layer := "^${LAYERDIR}/"
LAYERSERIES_COMPAT_trx40d8-2n2t-layer = "wrynose whinlatter"
